function [J,Jdot] = jac(in1,in2,l1,l2,l0)
%JAC
%    [J,JDOT] = JAC(IN1,IN2,L1,L2,L0)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    03-Apr-2018 17:49:57

q1 = in1(1,:);
q2 = in1(2,:);
q4 = in1(4,:);
q_d1 = in2(1,:);
q_d2 = in2(2,:);
q_d4 = in2(4,:);
t2 = cos(q1);
t3 = sin(q2);
t4 = cos(q2);
t5 = sin(q1);
t6 = l0-q4;
J = reshape([-l1.*t2-l2.*t2.*t4-t2.*t3.*t6,-l1.*t5-l2.*t4.*t5-t3.*t5.*t6,0.0,0.0,l2.*t3.*t5-t4.*t5.*t6,-l2.*t2.*t3+t2.*t4.*t6,l2.*t4+t3.*t6,0.0,0.0,0.0,0.0,1.0,t3.*t5,-t2.*t3,t4,0.0],[4,4]);
if nargout > 1
    Jdot = reshape([l1.*q_d1.*t5+q_d4.*t2.*t3+l2.*q_d2.*t2.*t3+l2.*q_d1.*t4.*t5-q_d2.*t2.*t4.*t6+q_d1.*t3.*t5.*t6,-l1.*q_d1.*t2+q_d4.*t3.*t5-l2.*q_d1.*t2.*t4+l2.*q_d2.*t3.*t5-q_d1.*t2.*t3.*t6-q_d2.*t4.*t5.*t6,0.0,0.0,q_d4.*t4.*t5+l2.*q_d1.*t2.*t3+l2.*q_d2.*t4.*t5-q_d1.*t2.*t4.*t6+q_d2.*t3.*t5.*t6,-q_d4.*t2.*t4-l2.*q_d2.*t2.*t4+l2.*q_d1.*t3.*t5-q_d2.*t2.*t3.*t6-q_d1.*t4.*t5.*t6,-q_d4.*t3-l2.*q_d2.*t3+q_d2.*t4.*t6,0.0,0.0,0.0,0.0,0.0,q_d1.*t2.*t3+q_d2.*t4.*t5,-q_d2.*t2.*t4+q_d1.*t3.*t5,-q_d2.*t3,0.0],[4,4]);
end
