function [J_link1,J_link2,J_link3,J_link4] = link_jacs(in1,l1,l2,l0)
%LINK_JACS
%    [J_LINK1,J_LINK2,J_LINK3,J_LINK4] = LINK_JACS(IN1,L1,L2,L0)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    03-Apr-2018 17:49:58

q1 = in1(1,:);
q2 = in1(2,:);
q4 = in1(4,:);
t2 = cos(q1);
t3 = sin(q1);
J_link1 = reshape([l1.*t2.*(-1.0./2.0),l1.*t3.*(-1.0./2.0),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[4,4]);
if nargout > 1
    t4 = cos(q2);
    t5 = sin(q2);
    J_link2 = reshape([-l1.*t2-l2.*t2.*t4.*(1.0./2.0),-l1.*t3-l2.*t3.*t4.*(1.0./2.0),0.0,0.0,l2.*t3.*t5.*(1.0./2.0),l2.*t2.*t5.*(-1.0./2.0),l2.*t4.*(1.0./2.0),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[4,4]);
end
if nargout > 2
    t6 = l2.*t3.*t5;
    t7 = l0-q4;
    t8 = l2.*t4;
    J_link3 = reshape([-l1.*t2-l2.*t2.*t4,-l1.*t3-l2.*t3.*t4,0.0,0.0,t6,-l2.*t2.*t5,t8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[4,4]);
end
if nargout > 3
    J_link4 = reshape([-l1.*t2-l2.*t2.*t4-t2.*t5.*t7,-l1.*t3-l2.*t3.*t4-t3.*t5.*t7,0.0,0.0,t6-t3.*t4.*t7,-l2.*t2.*t5+t2.*t4.*t7,t8+t5.*t7,0.0,0.0,0.0,0.0,1.0,t3.*t5,-t2.*t5,t4,0.0],[4,4]);
end
