function skew_matrix = hat(in1)
%HAT
%    SKEW_MATRIX = HAT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    14-Apr-2018 18:56:26

vector1 = in1(1,:);
vector2 = in1(2,:);
vector3 = in1(3,:);
skew_matrix = reshape([0.0,vector3,-vector2,-vector3,0.0,vector1,vector2,-vector1,0.0],[3,3]);
