function vector = inv_hat(in1)
%INV_HAT
%    VECTOR = INV_HAT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    14-Apr-2018 18:56:27

skew_matrix1_2 = in1(4);
skew_matrix1_3 = in1(7);
skew_matrix2_3 = in1(8);
vector = [-skew_matrix2_3;skew_matrix1_3;-skew_matrix1_2];
